In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('Computer-Vision-with-Python/DATA/bank_note_data.txt',delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler_object = MinMaxScaler()

In [13]:
scaler_object.fit(X_train) #Only X_train is fitted

MinMaxScaler()

In [14]:
scaled_X_train = scaler_object.transform(X_train)

In [15]:
scaled_X_test = scaler_object.transform(X_test)

In [16]:
from keras.models import Sequential
from keras.layers import Dense

In [17]:
model = Sequential()

model.add(Dense(4, input_dim=4, activation='relu')) # Input layer of NN

model.add(Dense(8, activation='relu')) # Hidden layer of NN

model.add(Dense(1, activation='sigmoid' )) # Output layer of NN

C:\Users\okeiy\.conda\envs\cvcourse_env\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 4)                   │              20 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 8)                   │              40 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 69 (276.00 B)

 Trainable params: 69 (276.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
29/29 - 2s - 83ms/step - accuracy: 0.5495 - loss: 0.6846
Epoch 2/50
29/29 - 0s - 7ms/step - accuracy: 0.5495 - loss: 0.6831
Epoch 3/50
29/29 - 0s - 6ms/step - accuracy: 0.5495 - loss: 0.6819
Epoch 4/50
29/29 - 0s - 5ms/step - accuracy: 0.5495 - loss: 0.6804
Epoch 5/50
29/29 - 0s - 5ms/step - accuracy: 0.5495 - loss: 0.6790
Epoch 6/50
29/29 - 0s - 5ms/step - accuracy: 0.5495 - loss: 0.6769
Epoch 7/50
29/29 - 0s - 5ms/step - accuracy: 0.5495 - loss: 0.6749
Epoch 8/50
29/29 - 0s - 5ms/step - accuracy: 0.5506 - loss: 0.6713
Epoch 9/50
29/29 - 0s - 5ms/step - accuracy: 0.5604 - loss: 0.6612
Epoch 10/50
29/29 - 0s - 5ms/step - accuracy: 0.5713 - loss: 0.6488
Epoch 11/50
29/29 - 0s - 4ms/step - accuracy: 0.5865 - loss: 0.6365
Epoch 12/50
29/29 - 0s - 6ms/step - accuracy: 0.6213 - loss: 0.6236
Epoch 13/50
29/29 - 0s - 13ms/step - accuracy: 0.6692 - loss: 0.6104
Epoch 14/50
29/29 - 0s - 16ms/step - accuracy: 0.6768 - loss: 0.5965
Epoch 15/50
29/29 - 0s - 7ms/step - accuracy: 0.7508 -

In [21]:
# model.predict(scaled_X_test)

In [22]:
model.metrics_names

['loss', 'compile_metrics']

In [23]:
from sklearn.metrics import confusion_matrix, classification_report

In [38]:
cm = confusion_matrix(y_test, predicted_classes) # Convert to 0 or 1

NameError: name 'predicted_classes' is not defined

In [28]:
predictions = model.predict(scaled_X_test)  # Outputs probabilities
predictions = (predictions > 0.5).astype(int)  # Convert to binary labels

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


In [31]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.93      0.98      0.96       257
         1.0       0.98      0.91      0.94       196

    accuracy                           0.95       453
   macro avg       0.96      0.95      0.95       453
weighted avg       0.95      0.95      0.95       453



In [32]:
model.save('mysupermodel.h5')

In [33]:
from keras.models import load_model

In [34]:
newmodel = load_model('mysupermodel.h5')

In [35]:
newmodel.predict(scaled_X_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step


array([[0.07276832],
       [0.4068616 ],
       [0.2807584 ],
       [0.10093529],
       [0.05558791],
       [0.03757691],
       [0.1916015 ],
       [0.01830732],
       [0.05195393],
       [0.13606353],
       [0.4727504 ],
       [0.81769353],
       [0.20139694],
       [0.8107874 ],
       [0.5568235 ],
       [0.2829414 ],
       [0.88010067],
       [0.8886831 ],
       [0.9024855 ],
       [0.81287783],
       [0.03535811],
       [0.09870673],
       [0.82410413],
       [0.02473125],
       [0.95431083],
       [0.02974146],
       [0.02358927],
       [0.8501849 ],
       [0.00975864],
       [0.01228866],
       [0.71143484],
       [0.12619996],
       [0.18792883],
       [0.9577778 ],
       [0.95582926],
       [0.01981895],
       [0.444891  ],
       [0.7478626 ],
       [0.8419533 ],
       [0.10836925],
       [0.08502776],
       [0.7081622 ],
       [0.7469918 ],
       [0.04246368],
       [0.9519514 ],
       [0.86969244],
       [0.921865  ],
       [0.061

In [36]:
predictions = newmodel.predict(X_test)  # Outputs probabilities
predictions = (predictions > 0.5).astype(int)  # Convert to binary labels

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 


In [37]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.96      0.99      0.97       257
         1.0       0.99      0.94      0.96       196

    accuracy                           0.97       453
   macro avg       0.97      0.97      0.97       453
weighted avg       0.97      0.97      0.97       453

